baseurl = "http://amyshi.me"
languageCode = "en-us"
title = "Amy Shi"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright notice"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "amyshi817"
    github = "amyshi188"
    linkedin = "daoyushi"
    instagram = "amyshi817"
    author = "Amy Shi"
    # avatar = "/path/to/avatar"
    contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "Student | Software Developer | Bookworm"
    # themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
