baseurl = "https://you.github.io/" 
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Amy Shi"
title = "Amy Shi"
pygmentsuseclasses = true
disqusShortname = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
Author = "Amy Shi"
CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "Don't panic"
Email = "amyshi@virginia.edu"
FaviconFile = "img/coffeebook.ico"
# GATracker = "XYZ"
GitHub = "//github.com/amyshi188"
HighlightJS = true
Initials = "ad" # Displayed on single post page; DEPRECATED in v0.3.0.
Lang = "en"
LinkedIn = "//linkedin.com/in/daoyushi"
Twitter = "//twitter.com/_amyshi_"
Instagram = "//instagram.com/_amyshi_"
ExtraCssFiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.